version: 2
jobs:
  build_docs:
    docker:
      - image: circleci/python:3.6-stretch
    steps:
      # Get our data and merge with upstream
      - run: sudo apt-get update
      - checkout

      - restore_cache:
          keys:
            - cache-pip

      - run: |
          pip install jupyter-book
      - save_cache:
          key: cache-pip
          paths:
            - ~/.cache/pip

      # Build the docs
      - run:
          name: Build docs to store
          command: |
            jb build .

      - store_artifacts:
          path: _build/html/
          destination: html


workflows:
  version: 2
  default:
    jobs:
      - build_docs
