# Prototype specification for clusters in service to Jupyter services
# For now, notebooks, thebe, and dashboards
swagger: '2.0'

info:
  version: "0.0.0"
  title: Binder API
  description: Binding computational resources and providing them on demand.
  contact:
    name: Jupyter project
    url: jupyter.org
basePath: /
produces:
  - application/json
consumes:
  - application/json
parameters:
  binderName:
    name: binderName
    required: true
    in: path
    description: name of a binder
    type: string

paths:
  /binders:
    get:
      description: Gets currently available binders
      responses:
        # Response code
        200:
          description: Successful response
          # A schema describing your response object.
          # Use JSON Schema format
          schema:
            title: ArrayOfBinders
            type: array
            items:
              $ref: '#/definitions/Binder'
    post:
      description: |
        Create new binders
      parameters:
        # An example parameter that is in query and is required
        - name: binder
          in: body
          schema:
            $ref: '#/definitions/Binder'
      # Expected responses for this operation:
      responses:
        # Response code
        200:
          description: Successfully created a binder spec
  /binders/{binderName}:
    parameters:
      - $ref: '#/parameters/binderName'
    get:
      description: Get the binder specification
      responses:
        200:
          description: asdfa
          schema:
            $ref: '#/definitions/Binder'
            
  /containers/{binderName}:
    parameters:
      - $ref: '#/parameters/binderName'
    post:
      description: launch a binder for use
      responses:
        200:
          description: triggered container launch
          schema:
            $ref: '#/definitions/Container'
  
                  
definitions:
  Binder:
    description: A specification for computational resources including data, requirements, notebooks, and services
    required:
      - name
      - repo
    properties:
      name:
        type: string
        description: name for the binder
      repo:
        type: string
        description: repository to pull contents from
      requirements:
        type: string
        description: location of requirements.txt in repository location
      notebooks:
        type: string
        description: location of notebooks within repository
      services:
        type: array
        items:
          $ref: '#/definitions/Service'
  Service:
    properties:
      name:
        type: string
      version:
        type: string
  Container:
    required:
      - id
    properties:
      id:
        type: string
      location: 
        type: string