name: deploy-book

# Only run this when the master branch changes
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

# Allow the bot to push to the repository
permissions:
  contents: write

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Install dependencies
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Build the docs
      run: |
        pip install nox
        nox -s docs

    # Push the book's HTML to github-pages
    - if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
      name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.5.9
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_build/html
